* Linux init file

  - .emacs

* Mac OSX

** Aquamacs init file

   Put it in  `~/Library/Preferences/Aquamacs Emacs/`

   - Preference.el
   - customizations.el

** Emacs

*** init file

    Put it in `~/.emacs.d`

    - init.el
    - .latexmkrc

*** Truc et astuces

**** Running Emacs.app from the command line

     Call this script "emacs" and put it somewhere in  `/usr/local/bin`:

     #+BEGIN_SRC shell
     #!/bin/sh
     /Applications/Emacs.app/Contents/MacOS/Emacs "$@"
     #+END_SRC

     Be sure to give it the execution permission.

     #+BEGIN_SRC shell
cd /usr/local/bin   
sudo chmod +x emacs 
     #+END_SRC


**** Changing the Modifier Keys

***** Easy

      The easiest way is to use the Customize interface: "M-x customize-group RET ns RET".

***** Hard

      If you don't like Customize and want to do it manually, the following variables control the modifier keys:

      - ns-alternate-modifier
      - ns-command-modifier
      - ns-control-modifier
      - ns-function-modifier
      - ns-option-modifier (just a different name for ns-alternate-modifier)
      - ns-right-alternate-modifier
      - ns-right-command-modifier
      - ns-right-control-modifier
      - ns-right-option-modifier

      Each variable can be set to 'control, 'meta, 'alt, 'super, or 'hyper.

      In addition ns-alternative-modifier (and ns-option-modifier) can be set to 'none, which lets it get interpreted by the OS so it can be used to input special characters.

      The ns-right-* variables are set to 'left by default which makes them the same as their left counterpart.
